### PR TITLE
Enable CI

### PR DESCRIPTION
**Pull request by aahna-ashina**
https://app.dework.xyz/nation3/develop-1?taskId=1e9abd16-3157-470f-bacd-987714d5d43d

### CODE REVIEW

**Review by tnrdd — COMMENTED** [review]
Given that this API is only usable when deployed on Vercel the development server can only be run with `vercel dev`.
Unfortunately this command [cannot be added](https://vercel.com/docs/errors#errors/recursive-invocation-of-commands) to `package.json` scripts so the user needs to invoke it.
To install Vercel CLI `npm install --global vercel` and run `vercel` to setup the project.

**Review by xPi2 — APPROVED** [review]

**Comment by xPi2** [comment]
> Given that this API is only usable when deployed on Vercel the development server can only be run with `vercel dev`. Unfortunately this command [cannot be added](https://vercel.com/docs/errors#errors/recursive-invocation-of-commands) to `package.json` scripts so the user needs to invoke it. To install Vercel CLI `npm install --global vercel` and run `vercel` to setup the project.

So there is now way the CI is going to pass?

**Comment by tnrdd** [comment]
> So there is no way the CI is going to pass?

It should pass the build job, the comment was about the README. Instead of `yarn dev` it should be `vercel dev`.

**Review by tnrdd — APPROVED** [review]

**Comment by aahna-ashina** [comment]
> Given that this API is only usable when deployed on Vercel the development server can only be run with `vercel dev`. Unfortunately this command [cannot be added](https://vercel.com/docs/errors#errors/recursive-invocation-of-commands) to `package.json` scripts so the user needs to invoke it. To install Vercel CLI `npm install --global vercel` and run `vercel` to setup the project.

@tnrdd Is it necessary to have access to Nation3's Vercel account for running `vercel dev`?  Or could it be _any_ Vercel account, even a developers personal Vercel account?

**Comment by tnrdd** [comment]
> @tnrdd Is it necessary to have access to Nation3's Vercel account for running `vercel dev`? Or could it be _any_ Vercel account, even a developer's personal Vercel account?
It's better if it's the developer personal account, the Nation3's account would only be required to deploy to the final custom domain.

**Pull request merged**
