### PR TITLE
Fix serverless function crash issue

### PR DESCRIPTION
**Pull request by biendeveloper**
Fixes https://github.com/nation3/token-supply/issues/6
This will be more stable than `getDefaultProvider` we can also remove unused variables from `.env`

### CODE REVIEW

**Review by aahna-ashina — COMMENTED** [review]
Thank you, @biendeveloper, this is a more stable solution 👍

I deployed to Vercel and tested https://token-supply-git-pr-7-aahna-ashina.vercel.app/api/circulating-supply and https://token-supply-git-pr-7-aahna-ashina.vercel.app/api/total-supply

Can you also delete the unused variables from `.env.sample`, please?
```
INFURA_ID= 
ALCHEMY_ID=
ETHERSCAN_ID=
```

**Comment by biendeveloper** [comment]
@aahna-ashina Thanks for testing! :) update env.sample

**Review by aahna-ashina — APPROVED** [review]

**Review by tnrdd — COMMENTED** [review]
This uses the Ankr public API, wouldn't it too incur in rate limits when there is a lot of traffic?
It doesn't have a fallback provider either so if Ankr's goes down the API goes down too.

I've found that the crash is because the Github integration pick up the `.env.sample` file without API keys instead of the Vercel one, apparently any file in the repo which name start with `.env` has the precedence.
Changing the file name to something like `example.env` would fix the issue while keeping 2 fallback providers.

**Comment by biendeveloper** [comment]
@tnrdd 
- I believe it won't hit the [ rate limit ](https://www.ankr.com/docs/build-blockchain/concepts/pricing/#public-and-premium-plans-comparison) Right now we are sending three calls per request, but we can use multicall to make it single contract call per request @aahna-ashina Let me know if we want to do it
- Agree with fallback but I believe it is not a necessity, we can always change to a different RPC
- I don't think changing the file name to something like example.env will actually fix this. can raise a PR to check? :) I guess there could be some configuration issue with Environment Variables in vercel UI itself, but I don't think it is worth maintaining three services API keys, I believe using a public node would be simple and powerful considering the use case :)

**Comment by aahna-ashina** [comment]
> * I believe it won't hit the [ rate limit ](https://www.ankr.com/docs/build-blockchain/concepts/pricing/#public-and-premium-plans-comparison) Right now we are sending three calls per request, but we can use multicall to make it single contract call per request @aahna-ashina Let me know if we want to do it

@biendeveloper I think this current solution works, as is.  So we just need one more PR approval from @nation3/developers so that we can merge it into `main`.

**Review by johnmark13 — APPROVED** [review]

**Review by luisivan — APPROVED** [review]

**Comment by aahna-ashina** [comment]
I tested https://token-supply.api.nation3.org/api/circulating-supply and https://token-supply.api.nation3.org/api/total-supply, and it's no longer crashing 👍

**Pull request merged**
